server:
  port: 8082
  servlet:
    context-path: /zen-service/api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      max-active: 8
      min-idle: 2
      maxWait: 60000
      url: jdbc:mysql://localhost:3306/easymap
      username: root
      password: Oracle
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  messages:
    basename: i18n/login
  thymeleaf:
    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true